package com.fliptle.app.auth

import android.content.Context
import android.os.Bundle
import android.view.View
import android.widget.Button
import android.widget.EditText
import android.widget.LinearLayout
import android.widget.TextView
import android.widget.Toast
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.fliptle.app.R
import com.google.android.gms.auth.api.signin.GoogleSignIn
import com.google.android.gms.auth.api.signin.GoogleSignInOptions
import com.google.android.gms.common.api.ApiException
import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.GoogleAuthProvider

/**
 * Free authentication (no billing): Google one-tap and email/password with the
 * built-in email-verification link. The user record and reinstall tracking are
 * keyed off the Firebase Auth UID. An optional parent phone number is collected
 * after sign-in as contact-only info (never used for login/verification).
 *
 * Auth is optional — core protection never depends on it.
 */
class SignInActivity : AppCompatActivity() {

    private var auth: FirebaseAuth? = null

    private lateinit var statusText: TextView
    private lateinit var emailInput: EditText
    private lateinit var passwordInput: EditText
    private lateinit var signInControls: LinearLayout
    private lateinit var phoneSection: LinearLayout
    private lateinit var parentPhoneInput: EditText

    private val googleLauncher = registerForActivityResult(
        ActivityResultContracts.StartActivityForResult()
    ) { result ->
        try {
            val account = GoogleSignIn.getSignedInAccountFromIntent(result.data)
                .getResult(ApiException::class.java)
            val idToken = account?.idToken
            if (idToken == null) {
                status(getString(R.string.auth_google_failed, "no ID token"))
                return@registerForActivityResult
            }
            val credential = GoogleAuthProvider.getCredential(idToken, null)
            auth?.signInWithCredential(credential)?.addOnCompleteListener(this) { task ->
                if (task.isSuccessful) onSignedIn("google") else
                    status(getString(R.string.auth_google_failed, task.exception?.message ?: ""))
            }
        } catch (e: ApiException) {
            status(getString(R.string.auth_google_failed, e.message ?: ""))
        }
    }

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_sign_in)

        statusText = findViewById(R.id.authStatusText)
        emailInput = findViewById(R.id.emailInput)
        passwordInput = findViewById(R.id.passwordInput)
        signInControls = findViewById(R.id.signInControls)
        phoneSection = findViewById(R.id.phoneSection)
        parentPhoneInput = findViewById(R.id.parentPhoneInput)

        if (!FirebaseGate.isAvailable(this)) {
            status(getString(R.string.firebase_not_configured))
            disableAll()
            return
        }
        auth = FirebaseAuth.getInstance()

        findViewById<Button>(R.id.googleSignInButton).setOnClickListener { startGoogleSignIn() }
        findViewById<Button>(R.id.emailSignUpButton).setOnClickListener { signUpEmail() }
        findViewById<Button>(R.id.emailSignInButton).setOnClickListener { signInEmail() }
        findViewById<Button>(R.id.savePhoneButton).setOnClickListener { saveParentPhone() }
        findViewById<Button>(R.id.skipPhoneButton).setOnClickListener { skipPhone() }

        auth?.currentUser?.let { showSignedInState() }
    }

    // ---- Google ----

    private fun startGoogleSignIn() {
        val webClientId = webClientId(this)
        if (webClientId == null) {
            status(getString(R.string.auth_google_unconfigured))
            return
        }
        val gso = GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
            .requestIdToken(webClientId)
            .requestEmail()
            .build()
        val client = GoogleSignIn.getClient(this, gso)
        client.signOut() // force the account chooser each time
        googleLauncher.launch(client.signInIntent)
    }

    /** default_web_client_id is generated by the Google Services plugin only when
     *  a Google OAuth client exists; look it up by name so the build never breaks. */
    private fun webClientId(context: Context): String? {
        val id = context.resources.getIdentifier("default_web_client_id", "string", context.packageName)
        return if (id != 0) context.getString(id) else null
    }

    // ---- Email / password ----

    private fun signUpEmail() {
        val email = emailInput.text.toString().trim()
        val pw = passwordInput.text.toString()
        if (email.isEmpty() || pw.length < 6) {
            Toast.makeText(this, R.string.auth_email_hint, Toast.LENGTH_SHORT).show()
            return
        }
        status(getString(R.string.auth_working))
        auth?.createUserWithEmailAndPassword(email, pw)?.addOnCompleteListener(this) { task ->
            if (task.isSuccessful) {
                auth?.currentUser?.sendEmailVerification()
                status(getString(R.string.auth_verify_sent, email))
                onSignedIn("password")
            } else {
                status(getString(R.string.auth_email_failed, task.exception?.message ?: ""))
            }
        }
    }

    private fun signInEmail() {
        val email = emailInput.text.toString().trim()
        val pw = passwordInput.text.toString()
        if (email.isEmpty() || pw.isEmpty()) {
            Toast.makeText(this, R.string.auth_email_hint, Toast.LENGTH_SHORT).show()
            return
        }
        status(getString(R.string.auth_working))
        auth?.signInWithEmailAndPassword(email, pw)?.addOnCompleteListener(this) { task ->
            if (task.isSuccessful) onSignedIn("password")
            else status(getString(R.string.auth_email_failed, task.exception?.message ?: ""))
        }
    }

    // ---- Shared ----

    private fun onSignedIn(method: String) {
        val user = auth?.currentUser ?: return
        showSignedInState()
        InstallTracker.recordSignIn(this, user.uid, user.email, method, AuthStore(this).installId()) { msg ->
            runOnUiThread {
                val verified = if (user.isEmailVerified) getString(R.string.auth_verified)
                else getString(R.string.auth_unverified)
                status("${getString(R.string.auth_signed_in, user.email ?: user.uid)}\n$verified\n$msg")
            }
        }
    }

    /**
     * After any sign-in method, reveal the parent-phone section identically. The
     * sign-in controls are hidden because sign-in is done. The phone number itself
     * is OPTIONAL for now — "Skip for now" proceeds without one (see PhoneGate,
     * whose enforcement switch is currently off).
     */
    private fun showSignedInState() {
        signInControls.visibility = View.GONE
        phoneSection.visibility = View.VISIBLE

        val store = AuthStore(this)
        // Prefill any number we already have on device.
        if (parentPhoneInput.text.isNullOrEmpty()) {
            store.signedInPhone?.let { parentPhoneInput.setText(it) }
        }
        // Best-effort: if this user already stored a phone (e.g. after a reinstall),
        // adopt it so they aren't needlessly re-prompted.
        val user = auth?.currentUser
        if (user != null && !store.parentPhoneProvided) {
            InstallTracker.fetchParentPhone(this, user.uid) { existing ->
                runOnUiThread {
                    if (!existing.isNullOrBlank()) {
                        store.signedInPhone = existing
                        store.parentPhoneProvided = true
                        if (parentPhoneInput.text.isNullOrEmpty()) parentPhoneInput.setText(existing)
                    }
                }
            }
        }
    }

    private fun saveParentPhone() {
        val user = auth?.currentUser
        if (user == null) {
            Toast.makeText(this, R.string.auth_email_hint, Toast.LENGTH_SHORT).show()
            return
        }
        val normalized = normalizePhone(parentPhoneInput.text.toString())
        if (normalized == null) {
            Toast.makeText(this, R.string.auth_phone_invalid, Toast.LENGTH_SHORT).show()
            return
        }
        // Save locally first (optimistic) so an offline user is never trapped by
        // the mandatory gate, then sync to Firestore under the same UID key.
        val store = AuthStore(this)
        store.signedInPhone = normalized
        store.parentPhoneProvided = true
        parentPhoneInput.setText(normalized)
        InstallTracker.saveParentPhone(this, user.uid, normalized) { msg ->
            runOnUiThread { Toast.makeText(this, msg, Toast.LENGTH_SHORT).show() }
        }
        Toast.makeText(this, R.string.auth_phone_saved, Toast.LENGTH_SHORT).show()
        finish()
    }

    /**
     * Skip the phone step for now (optional until the partner system ships). Marks
     * the phone as "handled" so the gate — if it is ever re-enabled — is satisfied,
     * and proceeds to the main app without saving a number.
     */
    private fun skipPhone() {
        AuthStore(this).parentPhoneProvided = true
        finish()
    }

    /**
     * Validate and normalize a plausible phone number. Keeps an optional single
     * leading '+' and the digits; requires 7–15 digits (E.164 caps at 15). Returns
     * null if it doesn't look like a real number.
     */
    private fun normalizePhone(raw: String): String? {
        val trimmed = raw.trim()
        val digits = trimmed.filter { it.isDigit() }
        if (digits.length < 7 || digits.length > 15) return null
        return if (trimmed.startsWith("+")) "+$digits" else digits
    }

    private fun disableAll() {
        for (id in intArrayOf(
            R.id.googleSignInButton, R.id.emailSignUpButton,
            R.id.emailSignInButton, R.id.savePhoneButton
        )) findViewById<Button>(id).isEnabled = false
    }

    private fun status(message: String) {
        statusText.text = message
    }
}
